/* AUTO-GENERATED by tools/optimize_spa_index_performance.py */
const CACHE_NAME = "mh-static-259fcbd4fd12";
const PRECACHE_URLS = [
  '/site-theme.css',
  '/site-pages.css',
  '/site-config.js',
  '/site-analytics.js',
  '/eisei1-data-glossary.js',
  '/eisei1-data-original.js',
  '/eisei1-master-data.js',
  '/eisei1-data-ichimon.js',
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (!PRECACHE_URLS.some((path) => url.pathname === path || url.pathname.endsWith(path))) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response && response.status === 200 && response.type === "basic") {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }
        return response;
      });
    })
  );
});
