#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""data/past_questions.csv と data/original_questions.csv（任意）→ eisei1-master-data.js（CSV_IMPORTED_*）。"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.site_config import category_to_field_map

DATA_CSV = ROOT / "data" / "past_questions.csv"
ORIG_CSV = ROOT / "data" / "original_questions.csv"
OUT_JS = ROOT / "eisei1-master-data.js"
OUT_ORIG_JS = ROOT / "eisei1-data-original.js"
OUT_JS_GENERIC = ROOT / "exam-site-data.js"
OUT_ORIG_JS_GENERIC = ROOT / "exam-site-data-original.js"

# オリジナル問題プール（index.html の isCsvOrigPoolQuestion / applyCsvImportedQuestions と対応）
ORIG_POOL_YEAR = "orig"
ORIG_ID_BASE = 900_000

LABELS = [("ア", "statement_a"), ("イ", "statement_b"), ("ウ", "statement_c"), ("エ", "statement_d")]

# site-config.json の fields[].aliases / name に対応
CATEGORY_TO_FIELD: dict[str, str] = category_to_field_map()


def norm(s: str | None) -> str:
    return (s or "").strip()


def build_plain_text(row: dict) -> str:
    parts: list[str] = []
    stem = norm(row.get("stem"))
    preamble = norm(row.get("preamble"))
    if stem:
        parts.append(stem)
    if preamble:
        parts.append(preamble)
    for lab, key in LABELS:
        t = norm(row.get(key))
        if t:
            parts.append(f"{lab}　{t}")
    return "\n\n".join(parts) if parts else "（問題文なし）"


def parse_correct(raw: str) -> int | None:
    raw = norm(raw)
    if not raw:
        return None
    try:
        n = int(raw)
    except ValueError:
        return None
    if 1 <= n <= 5:
        return n - 1
    return None


def row_to_obj(row: dict, line_no: int) -> dict | None:
    if norm(row.get("is_invalidated", "")).upper() == "TRUE":
        return None
    year = int(row["exam_year"])
    qno = int(row["question_no"])
    cat = norm(row.get("category"))
    field = CATEGORY_TO_FIELD.get(cat)
    if not field:
        raise ValueError(f"line {line_no}: 未対応の category={cat!r}")

    opts = [norm(row.get(f"choice_{i}")) for i in range(1, 6) if norm(row.get(f"choice_{i}"))]
    if not all(opts):
        raise ValueError(f"line {line_no}: 選択肢欠け year={year} no={qno}")

    inv = norm(row.get("is_invalidated", "")).upper() == "TRUE"
    cor = parse_correct(row.get("correct"))
    if cor is None and not inv:
        raise ValueError(f"line {line_no}: 正答なし year={year} no={qno}")

    text = build_plain_text(row)
    exp = norm(row.get("explanation")) or "（解説は未入力です。）"

    qid = year * 100 + qno
    return {
        "id": qid,
        "year": year,
        "num": qno,
        "field": field,
        "text": text,
        "opts": opts,
        "ans": 0 if cor is None else cor,
        "exp": exp,
    }


def orig_row_to_obj(row: dict, line_no: int) -> dict | None:
    """オリジナル問題 CSV（exam_year なし）。year は常に ORIG_POOL_YEAR。"""
    if norm(row.get("is_invalidated", "")).upper() == "TRUE":
        return None
    qno = int(row["question_no"])
    cat = norm(row.get("category"))
    field = CATEGORY_TO_FIELD.get(cat)
    if not field:
        raise ValueError(f"original_questions.csv line {line_no}: 未対応の category={cat!r}")

    opts = [norm(row.get(f"choice_{i}")) for i in range(1, 6) if norm(row.get(f"choice_{i}"))]
    if not all(opts):
        raise ValueError(f"original_questions.csv line {line_no}: 選択肢欠け no={qno}")

    cor = parse_correct(row.get("correct"))
    if cor is None:
        raise ValueError(f"original_questions.csv line {line_no}: 正答なし no={qno}")

    text = build_plain_text(row)
    exp = norm(row.get("explanation")) or "（解説は未入力です。）"
    qid = ORIG_ID_BASE + qno
    return {
        "id": qid,
        "year": ORIG_POOL_YEAR,
        "num": qno,
        "field": field,
        "text": text,
        "opts": opts,
        "ans": 0 if cor is None else cor,
        "exp": exp,
    }


def load_original_questions() -> list[dict]:
    if not ORIG_CSV.is_file():
        return []
    text = ORIG_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    out: list[dict] = []
    for i, row in enumerate(rows, start=2):
        o = orig_row_to_obj(row, i)
        if o is None:
            continue
        out.append(o)
    return out


def write_legacy_original_js(orig_objs: list[dict]) -> None:
    """index.html の旧オリジナル問題 UI 互換データも出力する。"""
    by_level: dict[int, list[dict]] = {1: [], 2: [], 3: []}
    for obj in orig_objs:
        q = dict(obj)
        q["level"] = 1
        q["unit"] = q.get("field", "")
        by_level[1].append(q)
    lines = [
        "/* AUTO-GENERATED by tools/csv_to_exam_site_master.py — data/original_questions.csv を編集し再生成 */",
        "const ORIG_QUESTIONS = " + json.dumps(by_level, ensure_ascii=False, indent=2) + ";",
    ]
    payload = "\n".join(lines) + "\n"
    OUT_ORIG_JS.write_text(payload, encoding="utf-8")
    OUT_ORIG_JS_GENERIC.write_text(payload, encoding="utf-8")


def main() -> int:
    if not DATA_CSV.is_file():
        print(f"入力がありません: {DATA_CSV}", file=sys.stderr)
        return 1
    text = DATA_CSV.read_text(encoding="utf-8-sig")
    rows = list(csv.DictReader(text.splitlines()))
    objs: list[dict] = []
    year_labels: dict[int, str] = {}
    for i, row in enumerate(rows, start=2):
        o = row_to_obj(row, i)
        if o is None:
            continue
        objs.append(o)
        y = o["year"]
        wl = norm(row.get("exam_wareki"))
        if y not in year_labels and wl:
            year_labels[y] = wl if y > 9999 else f"{wl}（{y}年）"

    orig_objs = load_original_questions()
    write_legacy_original_js(orig_objs)
    orig_years = [ORIG_POOL_YEAR] if orig_objs else []

    lines = [
        "// AUTO-GENERATED by tools/csv_to_exam_site_master.py — "
        "data/past_questions.csv / data/original_questions.csv を編集し再生成",
        "const CSV_IMPORTED_YEAR_LABELS = " + json.dumps(year_labels, ensure_ascii=False) + ";",
        "const CSV_IMPORTED_ORIG_POOL_YEARS = " + json.dumps(orig_years, ensure_ascii=False) + ";",
        "const CSV_IMPORTED_QUESTIONS = [",
    ]
    for o in objs:
        lines.append("  " + json.dumps(o, ensure_ascii=False) + ",")
    for o in orig_objs:
        lines.append("  " + json.dumps(o, ensure_ascii=False) + ",")
    lines.append("];")
    lines.append("")
    lines.append("if (typeof applyCsvImportedQuestions === 'function') {")
    lines.append("  applyCsvImportedQuestions();")
    lines.append("}")
    lines.append("")

    payload = "\n".join(lines)
    OUT_JS.write_text(payload, encoding="utf-8")
    OUT_JS_GENERIC.write_text(payload, encoding="utf-8")
    print(
        f"Wrote {OUT_JS} (過去問 {len(objs)} 問, オリジナル {len(orig_objs)} 問, 年度ラベル {len(year_labels)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
