#!/usr/bin/env python3
"""index.html SPA: defer データ JS・DOMContentLoaded 初期化・head へ theme/config・sw.js 生成。"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
DATA_SCRIPTS = (
    "eisei1-data-glossary.js",
    "eisei1-data-original.js",
    "eisei1-master-data.js",
    "eisei1-data-ichimon.js",
)
SW_ASSETS = (
    "/site-theme.css",
    "/site-pages.css",
    "/site-config.js",
    "/site-analytics.js",
    *(f"/{name}" for name in DATA_SCRIPTS),
)

HEAD_INJECT = """  <link rel="stylesheet" href="site-theme.css">
  <script defer src="site-config.js"></script>
"""

DOM_READY_OPEN = "document.addEventListener('DOMContentLoaded', function () {\n"
DOM_READY_CLOSE = "\n});\n"

MISSION_MARKER = "</script>\n<!-- MISSION COMPLETE POPUP -->"
ICHIMON_APP = '<script defer src="eisei1-data-ichimon.js"></script>\n<script>\n'
SECOND_SCRIPT_MARKER = "<!-- ===== 追加JavaScript ===== -->\n<script>\n"


def _cache_version() -> str:
    h = hashlib.sha256()
    for name in (*DATA_SCRIPTS, "site-theme.css", "site-pages.css", "site-config.js", "site-analytics.js"):
        p = ROOT / name
        if p.is_file():
            h.update(p.read_bytes())
    return h.hexdigest()[:12]


def write_service_worker() -> None:
    version = _cache_version()
    assets_js = ",\n  ".join(repr(a) for a in SW_ASSETS)
    body = f"""/* AUTO-GENERATED by tools/optimize_spa_index_performance.py */
const CACHE_NAME = "mh-static-{version}";
const PRECACHE_URLS = [
  {assets_js},
];

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (!PRECACHE_URLS.some((path) => url.pathname === path || url.pathname.endsWith(path))) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {{
      if (cached) return cached;
      return fetch(event.request).then((response) => {{
        if (response && response.status === 200 && response.type === "basic") {{
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }}
        return response;
      }});
    }})
  );
}});
"""
    (ROOT / "sw.js").write_text(body, encoding="utf-8")
    print(f"Wrote sw.js (cache id mh-static-{version})")


def optimize_index_html() -> bool:
    if not INDEX.is_file():
        print("index.html not found", file=__import__("sys").stderr)
        return False
    text = INDEX.read_text(encoding="utf-8")
    original = text

    head, rest = text.split("</head>", 1)
    if 'href="site-theme.css"' not in head:
        text = head + HEAD_INJECT + "</head>" + rest

    for name in DATA_SCRIPTS:
        text = text.replace(f'<script src="{name}"></script>', f'<script defer src="{name}"></script>')

    if ICHIMON_APP in text:
        ich_idx = text.find(ICHIMON_APP)
        after = text[ich_idx + len(ICHIMON_APP) : ich_idx + len(ICHIMON_APP) + 120]
        if "DOMContentLoaded" not in after:
            text = text.replace(ICHIMON_APP, ICHIMON_APP + DOM_READY_OPEN, 1)

    if MISSION_MARKER in text and DOM_READY_CLOSE.strip() not in text[
        max(0, text.find(MISSION_MARKER) - 200) : text.find(MISSION_MARKER)
    ]:
        text = text.replace(MISSION_MARKER, DOM_READY_CLOSE + MISSION_MARKER, 1)

    if SECOND_SCRIPT_MARKER in text:
        pos = text.find(SECOND_SCRIPT_MARKER)
        if DOM_READY_OPEN not in text[pos : pos + len(SECOND_SCRIPT_MARKER) + 80]:
            text = text.replace(SECOND_SCRIPT_MARKER, SECOND_SCRIPT_MARKER + DOM_READY_OPEN, 1)

    ga4 = "<!-- GA4: tools/html_footer.analytics_snippet"
    ga_idx = text.rfind(ga4)
    if ga_idx > 0:
        before_ga = text[:ga_idx]
        last_script_end = before_ga.rfind("</script>")
        tail = before_ga[max(0, last_script_end - 120) : last_script_end]
        if last_script_end > 0 and "});" not in tail:
            text = text[:last_script_end] + DOM_READY_CLOSE + text[last_script_end:]

    text = re.sub(
        r'\n<link rel="stylesheet" href="site-theme\.css">\n<script src="site-config\.js"></script>\n(?=<script defer src="site-analytics\.js">)',
        "\n",
        text,
        count=1,
    )

    sw_register = """<script>
if ("serviceWorker" in navigator) {
  window.addEventListener("load", function () {
    navigator.serviceWorker.register("/sw.js").catch(function () {});
  });
}
</script>
"""
    if 'register("/sw.js")' not in text:
        text = text.replace(
            '<script defer src="site-analytics.js"></script>\n</body>',
            '<script defer src="site-analytics.js"></script>\n' + sw_register + "</body>",
            1,
        )

    if text != original:
        INDEX.write_text(text, encoding="utf-8")
        print(f"Updated {INDEX.relative_to(ROOT)}")
        return True
    print("index.html already optimized")
    return False


def main() -> int:
    write_service_worker()
    optimize_index_html()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
