#!/usr/bin/env python3
"""index.html SPA: 非ブロック資産読み込み・動的データJS・sw.js・Lighthouse向け調整。"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
DATA_SCRIPTS = (
    "eisei1-data-glossary.js",
    "eisei1-data-original.js",
    "eisei1-master-data.js",
    "eisei1-data-ichimon.js",
)
LOAD_QUEUE = ("site-config.js", *DATA_SCRIPTS)

ASYNC_THEME_LINK = """  <link rel="preload" href="site-theme.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="site-theme.css"></noscript>
"""

def _data_bootstrap_html() -> str:
    queue = ", ".join(repr(n) for n in LOAD_QUEUE)
    ver = _cache_version()
    return f"""<script id="mh-spa-asset-bootstrap">
(function(){{
  window.__SPA_DATA_READY__ = false;
  function onSpaDataReady(fn) {{
    if (window.__SPA_DATA_READY__) {{ fn(); return; }}
    document.addEventListener("spa-data-ready", fn, {{ once: true }});
  }}
  window.onSpaDataReady = onSpaDataReady;
  var queue = [{queue}];
  var assetVer = "{ver}";
  function loadScript(src, done) {{
    var s = document.createElement("script");
    s.src = src + (src.indexOf("?") >= 0 ? "&" : "?") + "v=" + assetVer;
    s.onload = s.onerror = function () {{ done(); }};
    document.head.appendChild(s);
  }}
  function loadChain(i) {{
    if (i >= queue.length) {{
      window.__SPA_DATA_READY__ = true;
      document.dispatchEvent(new Event("spa-data-ready"));
      return;
    }}
    loadScript(queue[i], function () {{ loadChain(i + 1); }});
  }}
  function scheduleLoad() {{
    loadChain(0);
  }}
  if (document.readyState === "loading") {{
    document.addEventListener("DOMContentLoaded", scheduleLoad, {{ once: true }});
  }} else {{
    scheduleLoad();
  }}
}})();
</script>
"""

ANALYTICS_ENGAGEMENT = """<script>window.__GA4_MEASUREMENT_ID__="G-KRCW0FBHM8";</script>
<script defer src="site-analytics.js"></script>
"""

SYSTEM_FONT = (
    '--font: "Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic UI", "Yu Gothic", '
    '"Meiryo", sans-serif;'
)
SYSTEM_MONO = '--mono: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace;'

SPA_INDEX_CSS = "spa-index.css"

SW_REGISTER = """<script>
if ("serviceWorker" in navigator) {
  window.addEventListener("load", function () {
    navigator.serviceWorker.register("/sw.js").catch(function () {});
  });
}
</script>
"""

def _sw_assets() -> tuple[str, ...]:
    assets = [
        "/site-theme.css",
        "/site-pages.css",
        "/site-config.js",
        "/site-analytics.js",
        f"/{SPA_INDEX_CSS}",
        *(f"/{name}" for name in DATA_SCRIPTS),
    ]
    return tuple(assets)


def _cache_version() -> str:
    h = hashlib.sha256()
    for name in (*LOAD_QUEUE, "site-theme.css", "site-pages.css", "site-analytics.js", SPA_INDEX_CSS):
        p = ROOT / name
        if p.is_file():
            h.update(p.read_bytes())
    return h.hexdigest()[:12]


def write_service_worker() -> None:
    version = _cache_version()
    assets_js = ",\n  ".join(repr(a) for a in _sw_assets())
    body = f"""/* AUTO-GENERATED by tools/optimize_spa_index_performance.py */
const CACHE_NAME = "mh-static-{version}";
const PRECACHE_URLS = [
  {assets_js},
];

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (!PRECACHE_URLS.some((path) => url.pathname === path || url.pathname.endsWith(path))) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {{
      const network = fetch(event.request).then((response) => {{
        if (response && response.status === 200 && response.type === "basic") {{
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }}
        return response;
      }});
      return cached || network;
    }})
  );
}});
"""
    (ROOT / "sw.js").write_text(body, encoding="utf-8")
    print(f"Wrote sw.js (cache id mh-static-{version})")


def _remove_data_script_tags(text: str) -> str:
    for name in ("site-config.js", *DATA_SCRIPTS):
        text = re.sub(rf'\n<script defer src="{re.escape(name)}"></script>', "", text)
        text = re.sub(rf'\n<script src="{re.escape(name)}"></script>', "", text)
    return text


def _ensure_data_bootstrap(text: str) -> str:
    anchor = "  YEARS = Array.from(yset).sort(function (a, b) { return b - a; });\n}\n</script>\n"
    bootstrap = _data_bootstrap_html().rstrip() + "\n"
    if "mh-spa-asset-bootstrap" in text:
        return re.sub(
            r'<script id="mh-spa-asset-bootstrap">[\s\S]*?</script>\n+',
            bootstrap,
            text,
            count=1,
        )
    if anchor not in text:
        return text
    return text.replace(anchor, anchor + bootstrap, 1)


def _ensure_spa_boot_pattern(text: str) -> str:
    """gotoPage 等をグローバルに保つため、全コードを onSpaDataReady で包まない。"""
    if "function bootSpaApp()" in text and "onSpaDataReady(bootSpaApp)" in text:
        return text
    # 旧パターン（全コードラップ）を解除
    text = text.replace(
        "document.addEventListener('DOMContentLoaded', function () {\n  onSpaDataReady(function () {\n\n"
        "(function enrichGlossaryPlaceholderDesc",
        "(function enrichGlossaryPlaceholderDesc",
    )
    text = text.replace(
        "<!-- ===== 追加JavaScript ===== -->\n<script>\n"
        "document.addEventListener('DOMContentLoaded', function () {\n  onSpaDataReady(function () {\n",
        "<!-- ===== 追加JavaScript ===== -->\n<script>\n",
    )
    text = re.sub(
        r"\n  \}\);\n\}\);\n</script>\n<!-- GA4:",
        "\n</script>\n<!-- GA4:",
        text,
        count=1,
    )
    text = re.sub(
        r"\n  \}\);\n\}\);\n</script>\n<!-- MISSION COMPLETE POPUP -->",
        "\n</script>\n<!-- MISSION COMPLETE POPUP -->",
        text,
        count=1,
    )
    return text


def _use_system_fonts(text: str) -> str:
    for pattern in (
        r'\n<link rel="preconnect" href="https://fonts\.googleapis\.com">',
        r'\n<link rel="preconnect" href="https://fonts\.gstatic\.com" crossorigin>',
        r'\n<link rel="preload" as="style" href="https://fonts\.googleapis\.com[^"]+">',
        r'\n<link href="https://fonts\.googleapis\.com[^"]+" rel="stylesheet" media="print"[^>]*>',
        r'\n<noscript><link href="https://fonts\.googleapis\.com[^"]+" rel="stylesheet"></noscript>',
    ):
        text = re.sub(pattern, "", text)
    text = text.replace("--font:  'Noto Sans JP', sans-serif;", f"  {SYSTEM_FONT}")
    text = text.replace("--mono:  'Noto Sans JP', sans-serif;", f"  {SYSTEM_MONO}")
    text = re.sub(
        r"ctx\.font='(\d+[^']*) \"Noto Sans JP\", sans-serif'",
        r"ctx.font='\1 sans-serif'",
        text,
    )
    return text


def _externalize_spa_css(text: str) -> str:
    css_path = ROOT / SPA_INDEX_CSS
    if f'href="{SPA_INDEX_CSS}"' in text.split("</head>", 1)[0]:
        return text
    match = re.search(r"<style>\n(:root\s*\{)", text)
    if not match:
        return text
    start = match.start()
    end = text.find("</style>", start)
    if end < 0:
        return text
    css = text[start + len("<style>\n") : end]
    css_path.write_text(css, encoding="utf-8")
    link = (
        f'  <link rel="preload" href="{SPA_INDEX_CSS}" as="style" '
        'onload="this.onload=null;this.rel=\'stylesheet\'">\n'
        f'  <noscript><link rel="stylesheet" href="{SPA_INDEX_CSS}"></noscript>\n'
    )
    return text[:start] + link + text[end + len("</style>") :]


def _fix_chart_reflow(text: str) -> str:
    old = """function renderTrendChart(svgId,sessions){
  const svg=document.getElementById(svgId); if(!svg)return;
  const W=svg.parentElement.offsetWidth||700,H=220;"""
    new = """function renderTrendChart(svgId,sessions){
  const svg=document.getElementById(svgId); if(!svg)return;
  requestAnimationFrame(function(){
  const parent=svg.parentElement;
  const W=(parent&&parent.clientWidth)||700,H=220;"""
    if old not in text:
        return text
    text = text.replace(old, new, 1)
    needle = "  ${dateLabels}`;\n}\n\n// ===== QUIZ START ====="
    repl = "  ${dateLabels}`;\n  });\n}\n\n// ===== QUIZ START ====="
    return text.replace(needle, repl, 1) if needle in text else text


def _fix_head_assets(text: str) -> str:
    text = re.sub(
        r'\n\s*<link rel="stylesheet" href="site-theme\.css">\n\s*'
        r'<script defer src="site-config\.js"></script>\n',
        "\n" + ASYNC_THEME_LINK,
        text,
        count=1,
    )
    text = re.sub(
        r'\n\s*<link rel="stylesheet" href="site-theme\.css">\n',
        "\n" + ASYNC_THEME_LINK,
        text,
        count=1,
    )
    if 'href="site-theme.css"' not in text.split("</head>", 1)[0]:
        text = text.replace("</head>", "\n" + ASYNC_THEME_LINK + "</head>", 1)
    text = re.sub(r'\n\s*<script defer src="site-config\.js"></script>\n(?=</head>)', "\n", text, count=1)
    return text


def _fix_tooltip_reflow(text: str) -> str:
    old_block = """(function(){
  const el=document.getElementById('g-tooltip');
  document.addEventListener('mouseover',function(e){
    const icon=e.target.closest('.tip-icon');
    if(!icon) return;
    const box=icon.parentElement.querySelector('.tip-box');
    if(!box) return;
    el.textContent=box.textContent;
    el.style.display='block';
  });
  document.addEventListener('mousemove',function(e){
    if(el.style.display==='none') return;
    const x=e.clientX, y=e.clientY;
    const w=el.offsetWidth, h=el.offsetHeight;
    const vw=window.innerWidth, vh=window.innerHeight;
    let left=x+12, top=y-h-10;
    if(left+w>vw-8) left=x-w-12;
    if(top<8) top=y+16;
    el.style.left=left+'px';
    el.style.top=top+'px';
  });
  document.addEventListener('mouseout',function(e){
    if(e.target.closest('.tip-icon')) el.style.display='none';
  });
})();"""
    new_block = """(function(){
  const el=document.getElementById('g-tooltip');
  var tipW=0, tipH=0;
  document.addEventListener('mouseover',function(e){
    const icon=e.target.closest('.tip-icon');
    if(!icon) return;
    const box=icon.parentElement.querySelector('.tip-box');
    if(!box) return;
    el.textContent=box.textContent;
    el.style.display='block';
    tipW=el.offsetWidth;
    tipH=el.offsetHeight;
  });
  document.addEventListener('mousemove',function(e){
    if(el.style.display==='none') return;
    const x=e.clientX, y=e.clientY;
    const vw=window.innerWidth;
    let left=x+12, top=y-tipH-10;
    if(left+tipW>vw-8) left=x-tipW-12;
    if(top<8) top=y+16;
    el.style.left=left+'px';
    el.style.top=top+'px';
  });
  document.addEventListener('mouseout',function(e){
    if(e.target.closest('.tip-icon')) el.style.display='none';
  });
})();"""
    return text.replace(old_block, new_block, 1) if old_block in text else text


def _fix_analytics(text: str) -> str:
    ga_block = re.compile(
        r'<script>window\.__GA4_MEASUREMENT_ID__="[^"]*";</script>\s*'
        r'(?:<script>\s*\(function \(\) \{[\s\S]*?\}\)\(\);\s*</script>'
        r'|<script defer src="site-analytics\.js"></script>)',
        re.M,
    )
    text = ga_block.sub(ANALYTICS_ENGAGEMENT.strip(), text, count=1)
    if 'register("/sw.js")' not in text:
        text = text.replace("</body>", SW_REGISTER + "\n</body>", 1)
    return text


def optimize_index_html() -> bool:
    if not INDEX.is_file():
        print("index.html not found", file=__import__("sys").stderr)
        return False
    text = INDEX.read_text(encoding="utf-8")
    original = text
    text = _remove_data_script_tags(text)
    text = _use_system_fonts(text)
    text = _externalize_spa_css(text)
    text = _ensure_data_bootstrap(text)
    text = _ensure_spa_boot_pattern(text)
    text = _fix_head_assets(text)
    text = _fix_tooltip_reflow(text)
    text = _fix_chart_reflow(text)
    text = _fix_analytics(text)
    if text != original:
        INDEX.write_text(text, encoding="utf-8")
        print(f"Updated {INDEX.relative_to(ROOT)}")
        return True
    print("index.html already optimized")
    return False


def main() -> int:
    write_service_worker()
    optimize_index_html()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
